version: '3.7'
services:
  mysql-service:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    #    volumes:
    #      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financial
      MYSQL_USER: financial
      MYSQL_PASSWORD: financial

